Upwork_MVC/Models/Agreement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Upwork_MVC.Models
{
    public class Agreement
    {
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        [Display(Name ="Username")]
        public string UserId { get; set; }
        [Required]
        public int ProductId { get; set; }
        public Product Product { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Effective Date")]
        public DateTime EffectiveDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Expiration Date")]
        public DateTime ExpirationDate { get; set; }
        [Required]
        [Display(Name ="Product Price")]
        public decimal ProductPrice { get; set; }=decimal.Zero;
        [Required]
        [Display(Name = "New Price")]
        public decimal NewPrice { get; set; } = decimal.Zero;
    }

}

Upwork_MVC/Controllers/AgreementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Upwork_MVC.Data;
using Upwork_MVC.Models;

namespace Upwork_MVC.Controllers
{
    [Authorize]
    public class AgreementsController : Controller
    {
        private ProductAgreementDbContext db = new ProductAgreementDbContext();

        // GET: Agreements
        public async Task<ActionResult> Index()
        {
            var agreements = db.Agreements.Include(a => a.Product).Include(a => a.Product.ProductGroup);
            CreateLists();
            return View(await agreements.Take(500).ToListAsync());
        }

        // GET: Agreements/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agreement agreement = await db.Agreements.FindAsync(id);
            if (agreement == null)
            {
                return HttpNotFound();
            }
            return View(agreement);
        }
        [HttpGet]
        public async Task<ActionResult> GetAgreement(int id)
        {
            if (id > 0)
            {
                Agreement agreement = await db.Agreements.Where(v => v.Id == id).FirstOrDefaultAsync();
                return Json(agreement, JsonRequestBehavior.AllowGet);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        private void CreateLists()
        {
            ViewBag.ProductId = new SelectList(db.Products.OrderBy(o => o.ProductNumber), "Id", "ProductDescription");
        }

        // POST: Agreements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int? agreementId, string UserId, int ProductId, DateTime EffectiveDate, DateTime ExpirationDate, decimal ProductPrice, decimal NewPrice)
        {
            UserId = User.Identity.Name;
            Agreement agreement = PopulateAgreementCreate(agreementId, UserId, ProductId, EffectiveDate, ExpirationDate, ProductPrice, NewPrice);

            if (ModelState.IsValid)
            {
                db.Agreements.Add(agreement);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProductId = new SelectList(db.Products, "Id", "ProductDescription", agreement.ProductId);
            return View(agreement);
        }
        Agreement PopulateAgreementEdit(int? agreementId, string userId, int productId, string effectiveDate, string expirationDate, decimal productPrice, decimal newPrice)
        {
            Agreement agreement = agreement = db.Agreements.Where(v => v.Id == agreementId).FirstOrDefault();
            string dateString;
            DateTime date;
            if (ConvertDateFromString(effectiveDate, out dateString, out date))
            {
                agreement.EffectiveDate = date;
            }
            if (ConvertDateFromString(expirationDate, out dateString, out date))
            {
                agreement.ExpirationDate = date;
            }

            //agreement.UserId = userId;
            agreement.ProductId = productId;
            agreement.ProductPrice = productPrice;
            agreement.NewPrice = newPrice;
            return agreement;
        }
        Agreement PopulateAgreementCreate(int? agreementId, string userId, int productId, DateTime effectiveDate, DateTime expirationDate, decimal productPrice, decimal newPrice)
        {
            Agreement agreement = new Agreement();
            agreement.UserId = userId;
            agreement.ProductId = productId;
            agreement.EffectiveDate = effectiveDate;
            agreement.ExpirationDate = expirationDate;
            agreement.ProductPrice = productPrice;
            agreement.NewPrice = newPrice;
            return agreement;
        }

        private bool ConvertDateFromString(string effectiveDate, out string dateString, out DateTime date)
        {
            dateString = $"{effectiveDate.Substring(6, 4)}-{effectiveDate.Substring(0, 2)}-{effectiveDate.Substring(3, 2)} 00:00 AM";
            try
            {
                date = DateTime.ParseExact(dateString, "yyyy-MM-dd HH:mm tt", null);
            }
            catch (Exception)
            {
                date = DateTime.MinValue;
                return false;
            }
            return true;
        }

        // GET: Agreements/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agreement agreement = await db.Agreements.FindAsync(id);
            if (agreement == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "ProductDescription", agreement.ProductId);
            return View(agreement);
        }

        // POST: Agreements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? agreementId, string UserId, int ProductId, string EffectiveDate, string ExpirationDate, decimal ProductPrice, decimal NewPrice)
        {
            Agreement agreement = PopulateAgreementEdit(agreementId, UserId, ProductId, EffectiveDate, ExpirationDate, ProductPrice, NewPrice);
            if (ModelState.IsValid)
            {
                db.Entry(agreement).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = new SelectList(db.Products, "Id", "ProductDescription", agreement.ProductId);
            return View(agreement);
        }

        // GET: Agreements/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agreement agreement = await db.Agreements.FindAsync(id);
            if (agreement == null)
            {
                return HttpNotFound();
            }
            return View(agreement);
        }

        // POST: Agreements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int agreementId)
        {
            Agreement agreement = await db.Agreements.FindAsync(agreementId);
            db.Agreements.Remove(agreement);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Upwork_MVC/Views/Agreements/Create.cshtml
@model Upwork_MVC.Models.Agreement

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agreement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Upwork_MVC/Views/Agreements/CreateAgreementModal.cshtml
@using (Html.BeginForm("Create", "Agreements", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <!-- Modal -->
    <div id="AgreementModalCreate" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">New Agreement</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="AgreementId" id="AgreementId" />
                    <input type="hidden" name="UserId" id="UserId" />
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Product</label>
                            <div class="col-md-8">
                                @Html.DropDownList("ProductId", null, "-", htmlAttributes: new { @class = "form-control", @required = "required", autofocus = "autofocus" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Effective Date</label>
                            <div class="col-md-8">
                                <input type="date" required name="EffectiveDate" id="EffectiveDate" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Expiration Date</label>
                            <div class="col-md-8">
                                <input type="date" required name="ExpirationDate" id="ExpirationDate" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Product Price</label>
                            <div class="col-md-8">
                                <input type="number" required min="0" value="0" step="any" name="ProductPrice" id="ProductPrice" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">New Price</label>
                            <div class="col-md-8">
                                <input type="number" required min="0" value="0" step="any" name="NewPrice" id="NewPrice" class="form-control" />
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success btn-lg">Save</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

Upwork_MVC/Views/Agreements/Delete.cshtml
@model Upwork_MVC.Models.Agreement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agreement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Upwork_MVC/Views/Agreements/DeleteAgreementModal.cshtml
@using (Html.BeginForm("Delete", "Agreements", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <!-- Modal -->
    <div id="DeleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Delete Agreement ?</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="AgreementId" id="AgreementId" />
                    <p>Please confirm you wish to delete this agreement. Note this cannot be undone!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger btn-lg">Yes</button>
                </div>
            </div>

        </div>
    </div>

}

Upwork_MVC/Views/Agreements/Details.cshtml
@model Upwork_MVC.Models.Agreement

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agreement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NewPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NewPrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Upwork_MVC/Views/Agreements/Edit.cshtml
@model Upwork_MVC.Models.Agreement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agreement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EffectiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EffectiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Upwork_MVC/Views/Agreements/EditAgreementModal.cshtml
@using (Html.BeginForm("Edit", "Agreements", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <!-- Modal -->
    <div id="AgreementModalEdit" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit Agreement</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="AgreementId" id="AgreementId" />
                    <input type="hidden" name="UserId" id="UserId" />
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Product</label>
                            <div class="col-md-8">
                                @Html.DropDownList("ProductId", null, "-", htmlAttributes: new { @class = "form-control", @required = "required", autofocus = "autofocus" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Effective Date</label>
                            <div class="col-md-8">
                                <input minlength="10" maxlength="10" type="text" required name="EffectiveDate" id="EffectiveDate" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Expiration Date</label>
                            <div class="col-md-8">
                                <input minlength="10" maxlength="10" type="text" required name="ExpirationDate" id="ExpirationDate" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">Product Price</label>
                            <div class="col-md-8">
                                <input type="number" required min="0" value="0" step="any" name="ProductPrice" id="ProductPrice" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-4">New Price</label>
                            <div class="col-md-8">
                                <input type="number" required min="0" value="0" step="any" name="NewPrice" id="NewPrice" class="form-control" />
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success btn-lg">Save</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

Upwork_MVC/Views/Agreements/Index.cshtml
@model IEnumerable<Upwork_MVC.Models.Agreement>

@{
    ViewBag.Title = "Agreements";
}

<h2>🤝 Agreements</h2>

<table class="table table-bordered table-striped" id="table-agreements">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Username")
            </th>
            <th>
                @Html.DisplayName("Product Group Code")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.ProductNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NewPrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td title="@item.Product.ProductGroup.GroupDescription">
                    @Html.DisplayFor(modelItem => item.Product.ProductGroup.GroupCode)
                </td>
                <td title="@item.Product.ProductDescription">
                    @Html.DisplayFor(modelItem => item.Product.ProductNumber)
                </td>
                <td>
                    @item.EffectiveDate.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @item.ExpirationDate.ToString("MM/dd/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NewPrice)
                </td>
                <td class="btn-group-vertical">
                    <a href="#AgreementModalEdit" data-agreement-id="@item.Id" class="open-ModalEditAgreement btn btn-info btn-sm" data-toggle="modal" data-target="#AgreementModalEdit">
                        Edit
                    </a>
                    <a href="#DeleteModal" data-agreement-id="@item.Id" class="open-ModalDelete btn btn-danger btn-sm" data-toggle="modal" data-target="#DeleteModal">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#AgreementModalCreate">New Agreement</button>
</p>

@Html.Partial("CreateAgreementModal")
@Html.Partial("EditAgreementModal")
@Html.Partial("DeleteAgreementModal")




@section Scripts
    {


    <script>
        $(document).ready(function () {
            $('#table-agreements').DataTable({
                "order": [],
                "ordering": true,
                "buttons": true
            });
            $('input[type="search"]').focus();

        });
        $('.open-ModalDelete').on("click", function () {
            var id = $(this).data('agreement-id');
            console.log('Agreement Id:' + id);
            $(".modal-body #AgreementId").val(id);
        });
        $('.open-ModalEditAgreement').on("click", function () {
            var id = $(this).data('agreement-id');
            console.log('Agreement Id:' + id);
            $(".modal-body #AgreementId").val(id);
            $.ajax({
                type: "GET",
                url: "/Agreements/GetAgreement/" + id,
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ id: id }),
                dataType: "html",
                success: function (agreementResult) {
                    var data = JSON.parse(agreementResult);
                    $('.modal-body #UserId').val(data.Userid)
                    $('.modal-body #ProductId').val(data.ProductId)
                    var date = new Date(parseInt(data.EffectiveDate.substr(6)));
                    $('.modal-body #EffectiveDate').val(date.toISOString().substr(5, 2) + '/' + date.toISOString().substr(8, 2) + '/' + date.toISOString().substr(0, 4))
                    date = new Date(parseInt(data.ExpirationDate.substr(6)));
                    $('.modal-body #ExpirationDate').val(date.toISOString().substr(5, 2) + '/' + date.toISOString().substr(8, 2) + '/' + date.toISOString().substr(0, 4))
                    $('.modal-body #ProductPrice').val(data.ProductPrice)
                    $('.modal-body #ProductPrice').val(data.ProductPrice)
                    $('.modal-body #NewPrice').val(data.NewPrice)
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });
    </script>
}